PINCache/Nullability.h
PINCache/PINCache.h
PINCache/PINDiskCache.h
PINCache/PINMemoryCache.h
PINCache/nullability.h
tests/PINCache.xcodeproj/project.pbxproj

Nullability annotations is more friendly to Swift. Not break compatibility for Xcode less than 6.3.

Adopt nullability annotations for cleaner Swift headers

---

PINCache/PINDiskCache.m
tests/PINCache.xcodeproj/project.pbxproj

This should fix two issues:
- Because taskID was being captured before being set, the expiration handler had an invalid taskID.
- If the expiration handler was called, and then PINCacheEndBackgroundTask was called, it would try to end a task that had already ended.
The second case is less of an issue because I don't see it causing any problems. I've used an atomic getter / setter for taskID which should make it far less likely for there to be a race condition where endBackgroundTask is called twice with the same taskID. However it's still possible. Since this just seems to generate warnings, this seems better than the overhead of introducing a lock of some sort.

Invalid task ids used for expiration handlers. #13

---

PINCache/PINDiskCache.m
tests/PINCacheTests/PINCacheTests.m

- Change setup / tear down to use UUID as name. It is no longer safe to use two disk caches with the same name.
- Remove invalid test.
- Fix disk cache directories being created asynchronously.

Fix tests related to disk cache and conflicting names

---

PINCache/PINDiskCache.m
tests/PINCacheTests/PINCacheTests.m

Decrease byteCount by file's previous byteCount if updating object already in cache.

Fix PINDiskCache byteCount tracking

---

PINCache/PINDiskCache.m
tests/PINCacheTests/PINCacheTests.m

As mentioned in https://github.com/pinterest/PINCache/issues/41 I created a bugfix for https://github.com/pinterest/PINCache/pull/36
Maybe this should be unit tested, because it broke the complete DiskCache :sob:. I prepared a test for this but cannot access the private method!

[BUGFIX] Critical! String Encoding Bugfix

---

PINCache.podspec
PINCache/PINMemoryCache.m

Added support for watchOS 2

---

PINCache/PINMemoryCache.m

Further to discussion in https://github.com/pinterest/PINCache/pull/57 this PR cleans up date logic so that we only create the `NSDate` when we actually need to use it.

Only initialize NSDate when it is needed

---

PINCache/PINCache.m
PINCache/PINDiskCache.m
PINCache/PINMemoryCache.m

Should fix #51 
For the PINCache's objectForKey method I added a clang compiler pragma to suppress showing up the shadowing warnings. This is only for the weakSelf / strongSelf variables. There should be no other variables be shadowed anymore.
We could certainly go without the clang pragma, we should just come up with good names for all of this shadowed weakSelf / strongSelf variables than :)

Fix variable shadowing warnings

---

PINCache/PINDiskCache.m
tests/PINCacheTests/PINCacheTests.m

The current implementation doesn't escape %, so the following code fails:
```
[self decodedString:[self encodedString:@"%"]] // nil
```

Fixed bug that % is not properly escaped (PINDiskCache)

---

PINCache/PINDiskCache.h
PINCache/PINDiskCache.m
PINCache/PINMemoryCache.h
PINCache/PINMemoryCache.m
tests/PINCacheTests/PINCacheTests.m

In #32, I wanted to add what basically amounts to the ability to make the caches behave like a TTL cache. I've done this with tests, which I think clearly illustrate the behavior I was going for here. I'm pretty open to discussion on this, and I've made sure that this is opt-in, so existing behavior of the caches should be unaffected.

Added TTL cache capability

---

.travis.yml
PINCache.podspec
PINCache/PINDiskCache.m
PINCache/PINMemoryCache.m
build_tests.sh
tests/PINCache.xcodeproj/project.pbxproj
tests/PINCacheTests/PINCacheTests.m

- travis.yaml now runs ```pod lib lint```
- Fixed up build_tests.sh to work with recent xcode tools
- Fixed some async-related test failures/flakes

Fixed watchos linting errors

---

PINCache/PINDiskCache.m
tests/PINCacheTests/PINCacheTests.m

This is a minor bug we found when doing some more testing with the ttlCache behavior enabled. I missed that fileURLForKey: could also update PINDiskCache's file modification time. This fixes that.

Fixed fileURLForKey: updating the file modification date, when TTLCache is enabled

---

PINCache/PINDiskCache.h
tests/PINCacheTests/PINCacheTests.m

PINDiskCache's `fileURLForKey:` returns nil whenever the cache does not hold the object for the specified key.

Nullability correction

---

PINCache/PINDiskCache.m

For performance reasons move locking from a `dispatch_semaphore_t` to `pthread_mutex_t`.

Use pthread mutex instead of a semaphore for locking

---

PINCache/PINCache.h
PINCache/PINCache.m
PINCache/PINDiskCache.h
PINCache/PINDiskCache.m
tests/PINCacheTests/PINCacheTests.m

Separated from #101 
By default, files are stored using an escaped key. If I provide a serialiser / deserialiser that doesn't perform any operation on NSData objects, I can feed the file URLs directly into other API, in my case AVPlayerItem. Unfortunately, AVPlayerItem is particularly strict when it comes to reading file URLs and requires that there be an extension.
I have added a fileExtension property to PINDiskCache that is used after encoding a key.

Add support for a custom file extension

---

PINCache/PINOperationQueue.h
PINCache/PINOperationQueue.m
tests/PINCache.xcodeproj/project.pbxproj
tests/PINCacheTests/PINCacheTests.h
tests/PINCacheTests/PINCacheTests.m
tests/PINCacheTests/PINOperationQueueTests.m

PINOperationQueue is an operation queue designed to allow
specifying the maximum number of threads, support priority (ordering,
not thread priority and cancelation).
It is also designed to prevent live locks due to priority inversion.
It attempts to achieve this by maintaining two queues: a serial queue
which always takes operations in FIFO order and a concurrent queue
which runs operations in priority order.

Adds PINOperationQueue

---

PINCache/PINOperationQueue.h
PINCache/PINOperationQueue.m

Add support to cancel all operations. Furthermore created a new method for cancelling an operation that the lock needs to be hold. This used by `cancelOperation` as well as `cancelAllOperations` now.

Add cancelAllOperations to PINOperationQueue

---

PINCache/PINOperationQueue.h
PINCache/PINOperationQueue.m
tests/PINCacheTests/PINOperationQueueTests.m

Adding `waitUntilAllOperationsAreFinished` to `PINOperationQueue`. Should work the same as `waitUntilAllOperationsAreFinished` of `NSOperationQueue`
One use case could be if the operation queue is used as a transaction.

Add waitUntilAllOperationsAreFinished to PINOperationQueue

---

PINCache/PINCache.m

On lower end devices most operations end up being empty trash operations.
That issue needs to be addressed, but in the meantime, lets bump this
number up.

Increase max operation count to 10

---

PINCache/PINOperationQueue.m

On devices without multiple cores it's still useful to allow multiple
operations to run at once.
Hopefully addresses #134 134

Have sharedOperationQueue have at least 2 max operations.

---

PINCache/PINDiskCache.m
PINCache/PINOperationQueue.h
PINCache/PINOperationQueue.m
tests/PINCacheTests/PINCacheTests.m
tests/PINCacheTests/PINOperationQueueTests.m

Add a generic operation coallescing mechanism and use it to fix #135, #137.

Support operation coallescing

---

PINCache/PINCache.h
PINCache/PINCache.m
tests/PINCacheTests/PINCacheTests.m

This PR addresses issue #64 to expose methods on `PINCache` that accept a memory cache cost argument.

Support PINMemoryCache cost methods in PINCache

---

.buckconfig
BUCK
tests/BUCK

- Merge PINCacheCore, PINCache and PINCacheMacOS targets into a single target.
- Compile PINDishCache.m with -fobjc-arc-exceptions flag.
- Move test targets to a separate BUCK file. The main BUCK file can be re-used by users in their own projects after dependency resolution (i.e via CocoaPods).
- Remove unnecessary preprocessor flags.
- Now that we have multiple BUCK files, parse them in parallel.
- Specify default xctool destination.

Buck improvements

---

Source/PINDiskCache.h
Source/PINDiskCache.m

This exposes a method which given the parameters you would pass into
PINDiskCache would allow you to know the URL the disk cache will end
up being at.
It also allows setting the cache name prefix so it can be your application
identifier instead of com.pinterest.PINDiskCache.(name)

Expose cache URL class method and allow specification of name prefix

---

PINCache.xcodeproj/project.pbxproj
Source/PINCache.h
Source/PINCache.m
Source/PINCaching.h
Source/PINDiskCache.h
Source/PINDiskCache.m
Source/PINMemoryCache.h
Source/PINMemoryCache.m
Tests/PINCacheTests.m

The PINCaching protocol contains methods that all three cache classes are implementing and all declared in the header. With PINCaching we can have a consistent API across all components and could mostly remove some duplicated API definitions in the header files too.
Furthermore with this PR we will rename the asynchronous API's to a more expressive name.

Introduce PINCaching protocol

---

Source/PINDiskCache.h

On newer versions of clang, (specifically tested with 3.9), the
inclusion of the typedef in the deprecated section causes a build
failure (which I can't seem to suppress):
```
Redefinition of typedef 'PINDiskCacheObjectBlock' is a C11 feature
```

Redefined import error fix

---

Source/PINDiskCache.m
Tests/PINCacheTests.m

Encoding periods prevents mp4 files stored in `PINCache` from playing correctly in `AVFoundation`’s `AVPlayerItem` objects. To my knowledge it should be fine to leave periods unencoded.

Removes period from encoded characters

---

CHANGELOG.md
Source/PINCache.h
Source/PINCache.m
Source/PINDiskCache.h
Source/PINDiskCache.m
Tests/PINCacheTests.m

Hi.
First, thanks for an amazing project. We are using ASDK and PINRemoteImage extensively in our app. We started to use PINCache as separate cache and there are cases when we want our custom filenames. We have added block for custom custom encoding/decoding, so anyone can provide their implementation for filenames. This can be used also for file extensions. Maybe in the next version extension can be replaced with custom blocks. Please let us know if it’s okey to merge. 
Thanks.

added a way to set custom key encoder/decoder

---

CHANGELOG.md
Source/PINDiskCache.m
Tests/PINCacheTests.m

This serves as a mechanism for some clients, like users of the Texture framework, to
effectively disable the PINDiskCache by setting a byteLimit of 1.
Before this change, the cache would transiently exceed the byte limit by writing
the file anyway, and then immediately deleting it.
This change will not affect most users of PINDiskCache, but is important for this
specific use case.

[PINDiskCache] Respect small byteLimit settings by checking object size in setObject:

---

CHANGELOG.md
PINCache.xcodeproj/project.pbxproj
Source/PINCache.h
Source/PINCache.m
Source/PINCaching.h
Source/PINDiskCache.h
Source/PINDiskCache.m
Source/PINMemoryCache.h
Source/PINMemoryCache.m
Tests/NSDate+PINCacheTests.h
Tests/NSDate+PINCacheTests.m
Tests/PINCacheTests.m
Tests/PINDiskCache+PINCacheTests.h
Tests/PINDiskCache+PINCacheTests.m

I think this partially addresses #31.

Add ability to set an object level TTL

---

CHANGELOG.md
Source/PINDiskCache.m
Source/PINMemoryCache.m
Tests/PINCacheTests.m
Tests/PINDiskCache+PINCacheTests.h
Tests/PINDiskCache+PINCacheTests.m

This does two things:
1. Before this patch, PINCache was naively scheduling a task to trim to age limit *recursively* every time the age limit was set. This makes it so recursive calls are canceled when it detects another recursive call has been kicked off. This is still less than ideal :/
2. Trimming (mistakenly) used to be a high priority task. Now the age limit itself is set with a high priority, but the trimming is done at a low priority.

Improve performance of age limit trimming

---

CHANGELOG.md
Source/PINMemoryCache.m

If you want remove all objects, there is pointless to remove expired objects

Optimize `PINMemoryCache` remove objects when receive memory warning notification

---

Source/PINDiskCache.m

We can exit immediately when fileURL is invalid without acquiring and
then releasing the write lock.

Check fileURL outside of the locked scope

---

Source/PINDiskCache.m

Also wrap a conditional block in brackets for consistency with the rest
of this file.

Fix the grammar in an assertion failure message

---

PINCache.xcodeproj/project.pbxproj

Support Catalyst

---

Source/PINCache.m
Source/PINDiskCache.m
Source/PINMemoryCache.m

This beta added a diagnostic for passing more specific types to `id`-typed values:
> Fixed type checking for block parameters using id with protocols. The compiler now emits an error for method calls with a block that uses parameters more specific than arguments with which it will be called. (57980961)

Fix compiling in Xcode 12.0b4

---

Tests/PINCacheTests.m

Fixed type checking for block parameters in tests using id with
protocols. Same as commit 10b3c3c6 did.

Fix PINCacheTests compiling in Xcode 12.0b4

---

Source/PINCaching.h

Reference: https://reviews.llvm.org/D66831#2019125

Fix PINCaching compiling in Xcode 12.0b6 (#275)

---

.github/workflows/ci.yaml
.gitignore
Makefile
Package.swift
Source/PINCache.h
Source/PINCache.m
Source/PINDiskCache.h
Source/PINDiskCache.m
Source/PINMemoryCache.h
Source/PINMemoryCache.m
Tests/PINCacheTests.m
Tests/PINDiskCache+PINCacheTests.h
Tests/PINDiskCache+PINCacheTests.m

Added SPM support starting from Swift 5.3 (since it supports resources). Some notes:
- SPM tests not passing when you run it from a command line (SPM(bug)? gets the wrong bundle path) but passing if you use Xcode in SPM edit mode(just open as a package instead of .xcodeproj).
- dependency strategy for `PINOperation` set as - branch `master`. I believe it should be set - from `PINOperation 1.2.0` but unfortunately, it was tagged as `1.2` and SPM can not resolve it. Can the maintainers re-tag/new it with proper sem-ver?

Added SPM support

---

.github/workflows/ci.yaml
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration.xcodeproj/project.pbxproj
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration.xcodeproj/project.xcworkspace/contents.xcworkspacedata
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration.xcodeproj/xcshareddata/xcschemes/PINCache-SPM-Integration.xcscheme
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration/Assets.xcassets/AccentColor.colorset/Contents.json
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration/Assets.xcassets/AppIcon.appiconset/Contents.json
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration/Assets.xcassets/Contents.json
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration/ContentView.swift
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration/Info.plist
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration/PINCache_SPM_IntegrationApp.swift
IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration/Preview Content/Preview Assets.xcassets/Contents.json
Makefile
Source/PINCache.m
Source/PINDiskCache.m
Source/PINMemoryCache.m
Tests/PINCacheTests.m
carthage.sh

- without this change project itself can be built as spm package, but failed to do so when you integrate it as a dependency via Xcode.

Fixed spm integration on regular Xcode project.

---

Source/PINDiskCache.m

use _+unarchivedObjectOfClass:fromData:error:_ instead

+[NSKeyedUnarchiver unarchiveObjectWithData:] is deprecated on iOS 12

---

Source/PINDiskCache.h
Source/PINDiskCache.m

There's a bug currently where `PINDiskCache` will always trim cache size to 50MB when creating since it defaults to 50MB in the init, and immediately trims cache in `[self initializeDiskProperties];`. This is obviously not ideal since if we specify a cache size >50MB then we will constantly be having to refetch assets on each app open since it will trim to 50MB each time.
Proposed fix:
- Add two new fields to designated init to allow passing in custom `byteLimit` and `ageLimit`
- Keep convenience init to maintain API stability that defaults to 50MB/30 days

[Fix] Disk cache always trims cache to default size on creation

---

.github/workflows/ci.yaml
Makefile

This should hopefully fix up the CI

Stop specifying Xcode 12, no longer necessary

---

Source/PINMemoryCache.m

As the number of cached objects increases, sorting the accessDates becomes expensive. The access dates should only be sorted if the totalCost is greater than the limit.

Only sort accessDates if totalCost exceeds costLimit

---

Package.swift
PrivacyInfo.xcprivacy

Addresses #324.
See [Describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) for more information.
| Required Reason API Used          | Used in File                   |
|-----------------------------------|--------------------------------|
| NSFileModificationDate            | PINCache/Source/PINDiskCache.m |
| NSFileModificationDate            | PINCache/Tests/PINCacheTests.m |
| NSURLContentModificationDateKey   | PINCache/Source/PINDiskCache.m |
| NSURLCreationDateKey              | PINCache/Source/PINDiskCache.m |

Add PrivacyInfo.xcprivacy
