- tests/PINCacheTests/PINCacheTests.m
Added a handful of unit tests:
* `setObject`: setting the same key twice overwrites the original value
* `objectForKey`: getting a key that does not exist returns nil
* `removeAllObjects`: removes all objects from the cache
* `initWithName`: caches with the same name share the same contents
> Adding unit tests

- README.md
And 2 badges for both CocoaPods and Carthage.
> Update README for Carthage.

- PINCache/PINDiskCache.m
This was meant to go into a previous commit (thanks @jparise).
> Don't need to lock in initialization

- CHANGELOG.md
Please gloss over the updates but i looked at the diffs between versions and put together the most relevant changes 🖖
> updated changelog for v2 -> v2.1.2 to fix #48

- PINCache/PINCache.m
- PINCache/PINDiskCache.m
- PINCache/PINMemoryCache.m
- tests/PINCacheTests/PINCacheTests.m
> Fix static declarations

- CHANGELOG.md
- PINCache.podspec
- README.md
- Updated changelog
- Bumped podspec
- Cleaned up some white space in README.md
> 2.2.0 Release

- CHANGELOG.md
- PINCache.podspec
- Updated changelog
- Updated podspec
> PINCache 2.2.1 release

- PINCache/PINDiskCache.h
- PINCache/PINDiskCache.m
- tests/PINCacheTests/PINCacheTests.m
This PR adds file protection to files stored in the PINDiskCache.
The related issue is https://github.com/pinterest/PINCache/issues/81
> Add support for file writing protection

- PINCache/PINCache.h
- PINCache/PINCache.m
- PINCache/PINDiskCache.h
- PINCache/PINDiskCache.m
- PINCache/PINMemoryCache.h
- PINCache/PINMemoryCache.m
- tests/PINCacheTests/PINCacheTests.m
> Add API to determines whether an object is present for the given key in the cache

- PINCache/PINDiskCache.m
@johnezang and @appleguy brought up issues with background tasks and
performance (specifically in our app we were seeing the creation of the
tasks take a significant portion of all CPU time on single core devices).
Background tasks are created for the following actions:
- Emptying the trash
- Setting an object
- Removing an object
- Trimming the cache (size, date, size/date)
- Removing all objects
- Enumerating all objects
In the above list, only one task is truly necessary to complete to
avoid getting in an inconsistent state in a subsequent run, setObject:
After reasoning about it for  some time, I believe that creating
the background tasks is no longer necessary because of our try catch
on object unarchive.
The background tasks mainly ensure the cache stays in a consistent state …
> Remove background tasks

- PINCache/PINCache.h
- PINCache/PINCache.m
- PINCache/PINDiskCache.h
- PINCache/PINDiskCache.m
Particularly useful if you're unhappy with NSKeyedArchiver/unarchiver performance or want to encrypt persisted data.
> Added support for custom object serializer/deserializer

- PINCache/PINDiskCache.m
No need to hold the lock, and depending on what the client
is doing, they could be serializing / deserializing for a long
time.
> Avoid holding lock while serializing / deserializing

- tests/PINCache.xcodeproj/project.pbxproj
> Set Project to Use Spaces for Indentation

- PINCache/PINCache.h
- PINCache/PINMemoryCache.h
- PINCache/PINMemoryCache.m
@garrettmoon before you ask… yes, a semaphore killed my parents. 🙃
> [PINMemoryCache] Replace Semaphore with pthread_mutex

- PINCache/PINDiskCache.h
- PINCache/PINDiskCache.m
Expose the key on custom serializer. This way we can do any custom serialization based on different key.
> Expose key for custom serializer and deserializer

- PINCache.podspec
> Safe exceptions under ARC

- PINCache/PINOperationQueue.h
- PINCache/PINOperationQueue.m
Adds basic Nullability and Generics annotations.
> Add Nullability and Generics annotations

- PINCache.podspec
This reverts commit df836fbe3ba8da4698bd650962853e9486525b72.
> Revert "Revert beta 2 in podspec until we're ready to publish."

- PINCache/PINDiskCache.m
- tests/PINCacheTests/PINCacheTests.m
Follow up on #142 which was accidentally merged together with #141. 
cc #136, #137.
> Address comments and improve PINCacheTests

- tests/PINCacheTests/PINOperationQueueTests.m
> Test that blocks are not retained after run on operation queue

- README.md
> Add Swift examples to readmit and update Objective-C example to new async API

- Source/PINDiskCache.m
- Tests/PINCacheTests.m
Reverts pinterest/PINCache#181
> Revert "Removes period from encoded characters"

- CI/exclude-from-build.json
- README.md
> #trivial Fixes some links and formatting in the README.

- Source/PINDiskCache.m
Fixes https://github.com/pinterest/PINCache/issues/195
> #trivial print exception if deserialization fails

- CHANGELOG.md
- Source/PINDiskCache.m
Reduces a bunch of locks and unlocks hopefully on all trims.
> Refactoring to reduce a bunch of lock churn on cleanup.

- Source/PINCache.m
- Tests/PINCacheTests.m
> Propagate the name of the PINCache to the PINMemoryCache #trivial

- Source/PINDiskCache.h
Fixes #256 - Discrepancy between Header Comment and Implementation
> Discrepancy between Header Comment and Implementation #trivial

- Source/PINDiskCache.h
- Tests/PINCacheTests.m
Also remove an extra space from the PINDiskCacheObjectBlock type
definition.
> Test that the "remove object" blocks are called

- Source/PINDiskCache.m
- Tests/PINCacheTests.m
> Fix a race between -[removeAllObjects] and -[removeObjectForKey:] which could cause an item to not be removed

- Source/PINMemoryCache.m
Based on what @kchronis discovered, this should help prevent lock contention further.
> Don't hold lock while sorting
